### ISSUE TITLE
Rack-Cors & Rails 5 API: Whitelisting Domains

### ISSUE THREAD

**Issue by MsUzoAgu** [cyu/rack-cors#130]
I am having problems figuring out hot to configure rack-cors and would like some directions. 

Using the [rack-cors gem](https://github.com/cyu/rack-cors) in a rails 5 api-only application.  

The initializer `config/initializers/cors.rb` has the following:  

         Rails.application.config.middleware.insert_before 0, Rack::Cors do
           allow do
             origins 'http://somedomain.com'
    
             resource '*',
               headers: :any,
               methods: [:get, :post, :put, :patch, :options, :head]
           end
        end

To test things out, I made the following `curl` request:  
  
`curl -H "Origin: http://servere.com" --verbose localhost:3000`  

I expected to get a 400 response because the origin sent with the request does not match whitelisted origin in `config/initializers/cors.rb`.  Instead, I get back a 200 response. 

Checked the order in which the middlewares are initialized/called by running`rake middleware`. This prints a list that has `use Rack::Cors` at the top and `run AppName::Application.routes` at the bottom. From reading info on the internets, this appears to be right:  

- first `Rack::Cors` receives request, 
- check to make sure request can be passed on to  Rails Router (still not sure how this happens)  
  - if yes, pass on to routes,
  - if no, deny request and send back denial response 

I have opened up gem and tried using `debugger` to step into it and get a better idea of how it works but it doesn't even appear that Rack::Cors gets called at all. I am at a loss/confused as to what could be going wrong - specifically, why are non-whitelisted domains getting through. 

Any tips please?

**Comment by mateusluizfb** [comment]
Solution?

**Comment by jeduardo824** [comment]
Same problem here. @cyu do you have a solution for it?

**Comment by cyu** [comment]
Note this issue is closed.  I'm not sure what the specific issue here is (reading the description, I can see possibly more than one).

Keep in mind that `Rack::Cors` isn't an access control solution.  This middleware only returns the headers needed to satisfy CORS.  In cases of GET requests, those requests are passed to the app, even if they are not in the origin list. Keep in mind that by not returning valid CORS headers, compliant browsers will not allow the returned content to be available to the caller.  For other (POST, PUT, etc) requests, invalid Origins will not pass preflight, so the actual request should never be called.

Having said that, the middleware does provide information in the environment so that the app can block content if it needs to.
