### ISSUE TITLE
(Reason: CORS header ‘Access-Control-Allow-Origin’ missing)

### ISSUE THREAD

**Issue by ashwintastic** [cyu/rack-cors#137]
Hi team,
 my configuration is given below

               use Rack::Cors do
                           allow do
                             origins '*'
                             resource  '*',
                             headers: :any,
                            methods: [:post, :get, :options]
                         end
                     end
getting this error: 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9000/v2/user. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing

ruby version 2.3.1

**Comment by azizhk** [comment]
https://stackoverflow.com/questions/10883211/deadly-cors-when-http-localhost-is-the-origin

Chrome does not support localhost for CORS requests (an open bug since 2010).
To get around this you can use a domain like lvh.me (which points at 127.0.0.1 just like localhost) or start chrome with the --disable-web-security flag (assuming you're just testing).

**Comment by jakeonrails** [comment]
you can probably also add  a domain to your /etc/hosts if you're on mac/linux like:

```
127.0.0.1 my-rails-server.dev 
```

**Comment by cyu** [comment]
I'm closing this issue because there hasn't been any activity on this issue in a while.
