### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by BorisBresciani** [cyu/rack-cors#154]
Hello,

I do not really understand how to configure CORS with API and Front !

My situation:
API: api.com
Front: front.com (ReactJS with axios)

How do I tell the API to accept GET requests with URL (front.com), and if someone tries to do it via another URL (front-2.com), the API must reject this request .

Thank you for your help !

I tried but it does not work I put '*' or something at random in the origins the request passes anyway!

RUBY: 2.4.1
RAILS: 5.1.4

**Comment by cyu** [comment]
@BorisBresciani This gem doesn't block requests from passing through (with the exception of OPTION pre-flight requests).  The returns the proper headers for browsers for browsers to do the blocking.  What you need to check for for whether or not it is work is the presence of the **Access-Control-Allow-Origin** header in responses.

This gem does leave a `rack.cors` object in the context so that you can get the result of an origin/resource match.  So you can look at that and block the content.

**Comment by BorisBresciani** [comment]
As I understand it, this gem can just put a clean header. I need to check which side server or client? Client ??

How do I get the result of "rack.cors"?

**Comment by olimart** [comment]
@BorisBresciani set origins to 

```ruby
allow do
  origins 'http://front.com'
   # more config. here
end
```

**Comment by cyu** [comment]
I'm closing this issue because there hasn't been any activity in a while.

If you're still having problems. Please create a new issue and provide the specifics.
