### ISSUE TITLE
rack-cors does not support rails 4.2

### ISSUE THREAD

**Issue by KevinColemanInc** [cyu/rack-cors#193]
Rails 4 uses rack 1.6:

https://github.com/rails/rails/blob/4-2-stable/Gemfile.lock#L26

rack-cores calls [#unescaped](https://github.com/cyu/rack-cors/blob/master/lib/rack/cors.rb#L155) that was introduced [in rack 2.0.0](https://github.com/rack/rack/commit/978eb9b9935d388ca8cc45fe31c870b9bc0aaab2#diff-7c1a24d5b2fe58a6f925c7cacc6c55e7R46)

Suggested Fixes:

1. Drop support for rails 4.2 by updating the docs.
2. Support both

**Comment by typeoneerror** [comment]
@KevinColemanInc appears to be fixed in 1.0.6?

**Comment by cyu** [comment]
@KevinColemanInc version 1.0.6 should be compatible with Rails 4.2.  I used `unescape_path` in v1.0.5 which is a Rack 2.0.0 interface.

@typeoneerror I don't see this worthy of a major or minor version bump.  The API hasn't really change.  It's only breaking because I goofed up the versioning and dependency declaration.  Right now, if you run `bundle update` on a project, it will also update rack if you're below 1.6.0 and other dependencies allow it.  If other dependency don't allow an update to Rack 1.6.0, then Rack::Cors should fail to update as well.

Having said that, I just pushed out a version 1.1.0 that does require Rack 2.0.
