### ISSUE TITLE
Doesn't append Access-Control-Allow-Origin header as response

### ISSUE THREAD

**Issue by winston0410** [cyu/rack-cors#235]
I have following codes in `config/initializers/cors.rb`:

```ruby
Rails.application.config.middleware.insert_before 0, Rack::Cors do
  allow do
    origins '*'
    resource '*', headers: :any, methods: :any
  end
end
```

And when I try to do a request, I cannot see the `Access-Control-Allow-Origin` header in the response. I am using the latest rack-cors.

**Comment by davidalejandroaguilar** [comment]
Happened to me and turns out it was my Mac's Airplay Receiver (after Monterrey update) hijacking port 5000, so my app requests were hitting the Mac and of course, no CORS was configured there.

You can disable in System Preferences -> Sharing -> AirPlay Receiver.

More info here: https://developer.apple.com/forums/thread/682332

**Comment by swathi-ally** [comment]
If we are fetching the origin value from ENV var, what is the best way to do?
 ENV["VAR"] 
      or
ENV.fetch("VAR")

**Comment by MuhammadRazaAslam** [comment]
I'm also facing the same issue. Can we fix this issue on priority?

**Comment by cyu** [comment]
I'm closing this issue – there's not enough information to go on from information provided by @winston0410 @swathi-ally and @MuhammadRazaAslam 

Make sure you're providing an `Origin` header when testing – the middleware doesn't do anything unless that is provided.
