### ISSUE TITLE
Rails 5 deprecation warning

### ISSUE THREAD

**Issue by TangRufus** [cyu/rack-cors#92]
Rails 5 needs actual class references instead of strings or symbols.

```
01:37:52 log.1  | DEPRECATION WARNING: Passing strings or symbols to the middleware builder is deprecated, please change
01:37:52 log.1  | them to actual class references.  For example:
01:37:52 log.1  |
01:37:52 log.1  |   "Rack::Cors" => Rack::Cors
01:37:52 log.1  |
01:37:52 log.1  | . (called from block in tsort_each at /Users/******/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226)
```

**Comment by Biggless** [comment]
Remove initializer from config/application.rb
Create file config/initializers/rack_cors.rb with content
```
Rails.application.config.middleware.insert_before 0, Rack::Cors do
  allow do
    origins '*'
    resource '*', headers: :any, methods: [:get, :post, :put, :delete, :options]
  end
end
```

Hope it'll help :)

**Comment by sandeep45** [comment]
@Biggless solution also puts the Rack::Cors middleware on the top of the chain. This also solve other issues like `exceptions` showing CORS issue. These were being shown because earlier CORS middleware was after the `exceptions` middleware

**Comment by syndbg** [comment]
For future readers to sum the issue up - putting the initialization into a separate initialization file *does not solve the issue*.

What *actually solves the issue* is

```
config.middleware.insert_before 0, Rack::Cors do
```

Instead of

```
config.middleware.insert_before 0, 'Rack::Cors' do
```

**Comment by cyu** [comment]
@syndbg is correct solution to the deprecation warning is to use the class reference instead of string.  The Rails 5 example in the README reflects this.

While @biggless solution should also work, I'm using the `application.rb` syntax because that's currently the documented way to configure middleware according to the [Rails Guide](http://guides.rubyonrails.org/configuring.html#configuring-middleware)
